# Generated by Django 4.2.1 on 2023-07-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
