# Generated by Django 4.2.1 on 2023-07-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
